server:
  compression:
    enabled: false

logging:
  file: target/logs/application.log
  level:
    root: INFO
    com.gildata: INFO

spring:
  datasource:
    url: jdbc:h2:file:./target/work/h2db/db/demo;DB_CLOSE_DELAY=-1;
    username:
    password:
    max-active: 100
    max-idle: 20
    min-idle: 20
    initial-size: 50
    max-wait: 60000
    validation-query: SELECT 1
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
application:
  work:
    directory: work
